blank_issues_enabled: false
contact_links:
  - name: â“ Support Questions
    url: https://stackoverflow.com/questions/tagged/gland
    about: 'Please ask and answer support questions here instead of opening an issue.'
  - name: ğŸ’¬ Community Discussions
    url: https://github.com/glandjs/gland/discussions
    about: 'For feature discussions and general feedback, use GitHub Discussions.'